# data
dataset: 'kitti'  # 'kitti' or 'nyu'
kitti:
 data_dir: '/data/DepthRF/kitti/kitti_dp'
 split_json: '/home/ionut/DepthRF/src/datasets/kitti.json'
 num_sparse_points: 0
 patch_height: 352
 patch_width: 1216
 top_crop: 0
 test_crop: False
nyu:
 data_dir: '/data/DepthRF/nyudepthv2'
 split_json: '/home/ionut/DepthRF/src/datasets/nyu.json'
 num_sparse_points: 500
 height: 240
 width: 320
 crop_size: (228, 304)

#training
epochs: 20

# misc
device: 'cuda'
backbone_weights: '/home/ionut/DepthRF/src/weights/swin_large_patch4_window7_224_22k.pth'
model_weights: '/home/ionut/DepthRF/src/weights/swin_model_00035.pt' 
num_workers: 0
save_inference_images: True
max_depth: 80.0 
num_summary: 4
save_raw_npdepth: False
inference_steps: 20
num_train_timesteps: 1000
save_result_only: False